require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/news_items", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # NewsItem. As you add validations to NewsItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NewsItem.create! valid_attributes
      get news_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      news_item = NewsItem.create! valid_attributes
      get news_item_url(news_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_news_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      news_item = NewsItem.create! valid_attributes
      get edit_news_item_url(news_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NewsItem" do
        expect {
          post news_items_url, params: { news_item: valid_attributes }
        }.to change(NewsItem, :count).by(1)
      end

      it "redirects to the created news_item" do
        post news_items_url, params: { news_item: valid_attributes }
        expect(response).to redirect_to(news_item_url(NewsItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NewsItem" do
        expect {
          post news_items_url, params: { news_item: invalid_attributes }
        }.to change(NewsItem, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post news_items_url, params: { news_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested news_item" do
        news_item = NewsItem.create! valid_attributes
        patch news_item_url(news_item), params: { news_item: new_attributes }
        news_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the news_item" do
        news_item = NewsItem.create! valid_attributes
        patch news_item_url(news_item), params: { news_item: new_attributes }
        news_item.reload
        expect(response).to redirect_to(news_item_url(news_item))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        news_item = NewsItem.create! valid_attributes
        patch news_item_url(news_item), params: { news_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested news_item" do
      news_item = NewsItem.create! valid_attributes
      expect {
        delete news_item_url(news_item)
      }.to change(NewsItem, :count).by(-1)
    end

    it "redirects to the news_items list" do
      news_item = NewsItem.create! valid_attributes
      delete news_item_url(news_item)
      expect(response).to redirect_to(news_items_url)
    end
  end
end
